### ISSUE TITLE
Error: The requested accessory 'PJLink' was not registered by any plugin.

### ISSUE THREAD

**Issue by HunterDG** [emptygalaxy/homebridge-pjlink#2] opened 2021-01-16 03:20 UTC
upgraded from v0.1.0 to v1.0.1

tried v1.0.0, same issue

```
        {
            "name": "Living Room Projector",
            "ip": "10.0.1.225",
            "port": 4352,
            "password": "password",
            "manufacturer": "Epson",
            "model": "PowerLite 4855WU",
            "serialNumber": "xxxxxxxxx",
            "enableSwitch": false,
            "accessory": "PJLink"
        }
```

```
Error: The requested accessory 'PJLink' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:345:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
```

fwiw, v0.1.0 also has following error, but works as expected

```
Error: Unavailable time
    at Function.Response.getError (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:38:9)
    at Response.getError (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:33:18)
    at Command.InputCommand.Command.handleResponse (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/command.js:31:16)
    at PJLink._handleResponse (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:286:14)
    at PJLink._onData (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:206:8)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by emptygalaxy** [comment] 2021-01-26 11:19
Thanks for pointing that out, I'll update the repository to clearly point that out.
Because of API changes, the projectors showed as "unknown" types from iOS 14 showing a plain home icon instead of the familiar Television icon.
In order to comply with these changes, I've had to rewrite the plugin as platform instead of an accessory.
If you move the config to the "platforms" key like this, that should solve whatever issues you ran in to:
```
  "platforms": [
    {
      "name": "PJLink",
      "platform": "PJLink",
      "devices": [
        {
          "name": "Projector",
          "ip": "<ip x.x.x.x>",
          "port": 4352,
          "password": "<password>",
          "pollingInterval": 10
        }
      ]
    }
  ]

**Comment by emptygalaxy** [comment] 2021-01-26 11:30
The config.schema.json is now updated so you should also be able to use Config UI X to set up the plugin.

**Comment by muzzymate** [comment] 2021-01-28 17:55
Good afternoon,

Great to see movement again on this plugin! I used to use it before iOS14 and liked it because it exposed the projector as a TV rather than a light bulb. I just installed version 1.0.3 from the Homebridge-Config-UI-X Plugin menu and receiving a similar error message when starting Homebridge. This error puts Homebridge in an endless startup loop. I use the [Homebridge-VM-Image](https://github.com/homebridge/homebridge-vm-image) instance inside of Hyper-V.

```
[1/28/2021, 12:39:00 PM] ====================
[1/28/2021, 12:39:00 PM] ERROR LOADING PLUGIN homebridge-pjlink:
[1/28/2021, 12:39:00 PM] Error: Cannot find module 'PJLink'
Require stack:
- /homebridge/node_modules/homebridge-pjlink/dist/TelevisionHandler.js
- /homebridge/node_modules/homebridge-pjlink/dist/PJLinkPlatformAccessory.js
- /homebridge/node_modules/homebridge-pjlink/dist/PJLinkPlatform.js
- /homebridge/node_modules/homebridge-pjlink/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-pjlink/src/TelevisionHandler.ts:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

The configuration generated is included below but can confirm it was placed in the "platforms" block. Taking the configuration out does allow Homebridge to start. 

```
{
            "name": "Sanyo Projector",
            "devices": [
                {
                    "name": "Sanyo Projector",
                    "ip": "http://10.0.0.232/",
                    "port": 4352,
                    "password": "projector",
                    "manufacturer": "Sanyo",
                    "model": "PLC-WR251",
                    "inputs": [
                        {
                            "source": 1,
                            "channel": 1,
                            "name": "HDMI"
                        }
                    ],
                    "enableSwitch": true
                }
            ],
            "platform": "PJLink"
        }
```

**Comment by HunterDG** [comment] 2021-01-31 03:04
> The config.schema.json is now updated so you should also be able to use Config UI X to set up the plugin.

Thanks - I deleted old config, updated the plugin, and used Config UI X, but it was not successful - it placed the config in the accessories section.  After I manually moved config to platforms section, homebridge loaded successfully.  

I'm also still getting the "unavailable time" errors in the logs (mentioned at the end of 
https://github.com/emptygalaxy/homebridge-pjlink/issues/2#issue-787335854)

**Comment by evski** [comment] 2021-01-31 19:06
Hi, great plug-in thanks! I just tried uninstall after the update and then clean install and re-entering config. All looks fine in config.Json but bet this error on startup:

`Error: The requested platform 'PJLink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
`

**Comment by HunterDG** [comment] 2021-01-31 20:15
can confirm the exact same working config in Homebridge on Mac fails with `Error: The requested platform 'PJLink' was not registered by any plugin.` when used in [Homebridge-VM-Image](https://github.com/homebridge/homebridge-vm-image) instance inside of VirtualBox

I initially started from scratch, and Config UI X did place the config in the platforms section.  Eventually decided I'd just duplicate the working config (and plugins) into the VM, but it still fails.

**Comment by muzzymate** [comment] 2021-02-03 19:06
Thanks HunterDG. I can confirm that the plugin works when I tried it on a Windows 10 installation of Homebridge.

Seems to be isolated to the official boot2docker [Homebridge-VM-Image](https://github.com/homebridge/homebridge-vm-image).

**Comment by emptygalaxy** [comment] 2021-02-05 23:07
I run it on a Mac as well, just not in Homebridge-VM-Image, so that should not be a problem.
Any other logs you can share about the VM-Image issue?

**Comment by muzzymate** [comment] 2021-02-06 03:02
```
[2/5/2021, 9:48:26 PM] [HB Supervisor] Restarting Homebridge...
[2/5/2021, 9:48:26 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[2/5/2021, 9:48:26 PM] [HB Supervisor] Started Homebridge v1.2.5 with PID: 1190
[2/5/2021, 9:48:26 PM] Loaded config.json with 0 accessories and 2 platforms.
[2/5/2021, 9:48:26 PM] ---
[2/5/2021, 9:48:26 PM] ====================
[2/5/2021, 9:48:26 PM] ERROR LOADING PLUGIN homebridge-pjlink:
[2/5/2021, 9:48:26 PM] Error: Cannot find module 'PJLink'
Require stack:
- /homebridge/node_modules/homebridge-pjlink/dist/TelevisionHandler.js
- /homebridge/node_modules/homebridge-pjlink/dist/PJLinkPlatformAccessory.js
- /homebridge/node_modules/homebridge-pjlink/dist/PJLinkPlatform.js
- /homebridge/node_modules/homebridge-pjlink/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-pjlink/src/TelevisionHandler.ts:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[2/5/2021, 9:48:26 PM] ====================
[2/5/2021, 9:48:27 PM] Loaded plugin: homebridge-config-ui-x@4.37.0
[2/5/2021, 9:48:27 PM] Registering platform 'homebridge-config-ui-x.config'
[2/5/2021, 9:48:27 PM] ---
[2/5/2021, 9:48:27 PM] Loading 2 platforms...
[2/5/2021, 9:48:27 PM] [Config] Initializing config platform...
[2/5/2021, 9:48:27 PM] [Config] Running in Service Mode
[2/5/2021, 9:48:27 PM] Error loading platform requested in your config.json at position 2
[2/5/2021, 9:48:27 PM] Error: The requested platform 'PJLink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
[2/5/2021, 9:48:27 PM] Got SIGTERM, shutting down Homebridge...
[2/5/2021, 9:48:32 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

I'm not sure if this adds anything more than what's already been posted, but I just created a brand new install of the Homebridge-VM-Image and installed and configured the PJLink plugin. Run it with the debug mode flag set.  The generated information in config.json matches what is working in the Homebridge install on my Windows install. 

`    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "PJLink",
            "devices": [
                {
                    "name": "Sanyo Projector",
                    "ip": "10.0.0.232",
                    "port": 4352,
                    "password": "pjlink",
                    "manufacturer": "Sanyo",
                    "model": "PLC-WR251",
                    "version": "1.000",
                    "inputs": [
                        {
                            "source": 3,
                            "channel": 1,
                            "name": "HDMI"
                        }
                    ]
                }
            ],
            "platform": "PJLink"
        }
    ]`

Installing the plugin seems to report things are ok... If you can think of any logs that would be helpful for you, I'm happy to pull them, but I'm not sure what those would be. 

`root@homebridge-vm:/homebridge# npm install -g homebridge-pjlink
+ homebridge-pjlink@1.0.4
added 3 packages from 4 contributors in 1.293s`

**Comment by muzzymate** [comment] 2021-02-25 22:29
Hi @emptygalaxy, it's me again.

I just set up a new Ubuntu install, installed Homebridge, Homebridge-Config-ui-X, and Homebridge-PJLink. The same error is occurring there as well. One nagging commonality between what I've seen reported working and not working: installs on file case insensitive systems (Windows, Mac) are working correctly; installs on case sensitive file systems (Linux install, Docker install) are reporting the error below. Could there be a wrong case in an include/import of a file somewhere in the code? The other commonality would be both non-working installs are Linux based (I'm not sure where @evski's instal occurred but it looks Unix based) and something in the install process is not properly registering everything.

```
[2/25/2021, 5:16:38 PM] ====================
[2/25/2021, 5:16:38 PM] ERROR LOADING PLUGIN homebridge-pjlink:
[2/25/2021, 5:16:38 PM] Error: Cannot find module 'PJLink'
Require stack:
- /usr/lib/node_modules/homebridge-pjlink/dist/TelevisionHandler.js
- /usr/lib/node_modules/homebridge-pjlink/dist/PJLinkPlatformAccessory.js
- /usr/lib/node_modules/homebridge-pjlink/dist/PJLinkPlatform.js
- /usr/lib/node_modules/homebridge-pjlink/dist/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-pjlink/src/TelevisionHandler.ts:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[2/25/2021, 5:16:38 PM] ====================
```

Stats:
OS: Ubuntu Focal Fossa (20.04.2 LTS)
Node.js Version: v14.16.0
Npm Version: v6.14.11

**Comment by emptygalaxy** [comment] 2021-02-26 11:33
That could very well explain the issue here. Thanks for pointing me to the right direction, it does look like that was the problem. It was importing 'PJLink' instead of 'pjlink'. I've issued a patch on v1.0.5, please see if that fixes it.

**Comment by muzzymate** [comment] 2021-02-26 14:17
Yep! That did it. Now initializing and working correctly in my primary Homebridge-VM-Image and the test Ubuntu install. Windows install continues to work (and I'll now be getting rid of it since I'm fully migrated over to Homebridge-VM-Image). Thank you so much!!!

@evski - Does upgrading to version 1.0.5 version of the plugin fix your issue, too? I suspect it might. If so, I think this issue can be closed out.

**Comment by HunterDG** [comment] 2021-02-26 23:04
This has indeed solved the issue for me as well!   Thanks @muzzymate for the troubleshooting!

Anyone else experiencing the additional (non-breaking) errors in the logs (below)?  Should I open another issue?   Thought it was perhaps an issue with my specific Homebridge (native Mac), but seeing same error in Homebridge official VM ISO

```
[2/26/2021, 5:02:59 PM] [PJLink] Error: Unavailable time
    at Function.Response.getError (/homebridge/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:38:9)
    at Response.getError (/homebridge/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:33:18)
    at Command.InputCommand.Command.handleResponse (/homebridge/node_modules/homebridge-pjlink/node_modules/pjlink/lib/command.js:31:16)
    at PJLink._handleResponse (/homebridge/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:286:14)
    at PJLink._onData (/homebridge/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:206:8)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by evski** [comment] 2021-02-27 09:32
@muzzymate I upgraded to latest version had to delete old from config and readd config in homebridgeUI. After reboot I now get following error (all fields populated in config):

[2/27/2021, 09:26:24] [PJLink] get active identifier undefined
[2/27/2021, 09:26:25] [homebridge-pjlink] This plugin generated a warning from the characteristic 'Active Identifier': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info.
[2/27/2021, 09:26:25] [PJLink] Error: Authorization failed
    at Function.Response.getError (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:38:9)
    at Response.getError (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/response.js:33:18)
    at Command.PowerCommand.Command.handleResponse (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/command.js:31:16)
    at PJLink._handleResponse (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:286:14)
    at PJLink._onData (/usr/local/lib/node_modules/homebridge-pjlink/node_modules/pjlink/lib/pjlink.js:206:8)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base

**Comment by evski** [comment] 2021-02-27 20:28
I started from scratch again, uninstalled plugin, manually cleared config, then reinstalled and configured through hombridgeUI, fyi I'm running on raspberry pi. It then booted without errors, but said removing retired accessories and didn't show up in home app, so I added the accessory manually using my home bridge code and now all working! Thanks guys.

**Comment by emptygalaxy** [comment] 2021-02-28 12:18
Great to hear. I see the warning about the characteristic is popping up, but it shouldn't prevent it to work. I'll see if I can fix that in the near future.
``` This plugin generated a warning from the characteristic 'Active Identifier': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info. ```

For now I'll close this issue, please let me know if anything else comes up.

**Closed as completed by emptygalaxy** 2021-02-28 12:18 UTC
